### ISSUE TITLE
Feature Request: Add ArchiveBox to Umbrel App Store

### ISSUE THREAD

**Issue by pirate** [ArchiveBox/ArchiveBox#986]
Umbrel is a new OS for homelab self-hosting of Dockerized apps. It looks like a perfect fit for ArchiveBox and it's not difficult for us to add the yaml/config necessary to submit it to their App Store.

**Instructions:** https://github.com/getumbrel/umbrel-apps/blob/master/README.md

**TODOs:**
- [ ] Create `umbrel-apps/archivebox/docker-compose.yml` based on `archivebox/docker-compose.yml`
- [ ] Create `umbrel-apps/archivebox/umbrel-app.yml` The app manifest file telling Umbrel how to configure/deploy ArchiveBox
- [ ] Create `umbrel-apps/archivebox/exports.sh` The shell script to export environment variables used within the Umbrel `docker-compose.yml`

![image](https://user-images.githubusercontent.com/511499/172737401-8780eaf1-a002-4952-a094-24b4a18a8816.png)

Contributors wanted!
